name: detekt

on:
  push:
    branches: [ master ]

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3

      - name: Setup and build
        uses: gradle/gradle-build-action@v2.10.0
        env:
          CI: true
        with:
          arguments: build
