name: detekt

on:
  push:
    branches: [ master ]

jobs:
    detekt:
      runs-on: ubuntu-latest

      steps:
        - name: Setup and build
          uses: gradle/gradle-build-action@v2
          env:
            CI: true
          with:
            arguments: build