name: CI

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  run_detekt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 20
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Cache Gradlew packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      - name: Run detekt
        run: ./gradlew detekt